# Ansible managed
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: challenge




rule_files:
  - /etc/prometheus/rules/*.rules


scrape_configs:
  - job_name: weather1
    metrics_path: /
    static_configs:
    - targets:
      - 192.168.99.13:8000
  - job_name: weather2
    metrics_path: /
    static_configs:
    - targets:
      - 192.168.99.14:8000

  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - 192.168.99.12:9090
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node

